version: "3.9"

services:
  web:
    container_name: web
    build:
      context: ..
      dockerfile: deploy/web/Dockerfile.win
    env_file:
      - ../.env
    volumes:
      - ../data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - testssl.sh

  testssl.sh:
    container_name: testssl.sh
    image: drwetter/testssl.sh:latest
    volumes:
      - ../data:/data
    environment:
      - MASS_TESTING_MODE=parallel
    command: "--file /data/${TEST_SSL_INPUT_FILE} --jsonfile /data/${TEST_SSL_OUTPUT_FILE} --parallel --protocols --server-defaults --overwrite"