version: "3.9"

services:
  web:
    container_name: web
    build:
      context: ..
      dockerfile: deploy/web/Dockerfile.win
    env_file:
      - ../.env
    volumes:
      - ../data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - clickhouse
      - testssl.sh
    networks:
      - clickhouse-network

  testssl.sh:
    container_name: testssl.sh
    build:
      context: ..
      dockerfile: deploy/testssl.Dockerfile
    environment:
      - MASS_TESTING_MODE=parallel
    env_file:
      - ../.env
    deploy:
      resources:
        reservations:
          cpus: "4"
          memory: 4G

  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - ${CLICKHOUSE_PORT}:8123
      - 9000:9000
    env_file:
      - ../.env
    networks:
      - clickhouse-network
    volumes:
      - clickhouse-data:/var/lib/clickhouse/


volumes:
  clickhouse-data:

networks:
  clickhouse-network:
    driver: bridge